# NumPy — Introduction

In [ ]:
# Day 15 — NumPy (Numerical Python)
# Our FIRST external library! Until now we only used Python's built-in features.
# Today we start using libraries — pre-built code written by others that we can import and use.

# What we'll cover today:
#   1. What are Python libraries & how to use documentation
#   2. Why NumPy? (what problems does it solve that Python lists can't)
#   3. Installing and importing NumPy
#   4. Creating NumPy arrays
#   5. Type coercion (homogeneity rule)
#   6. Array dimensions — 0D, 1D, 2D, 3D
#   7. Array attributes — ndim, shape, size, dtype

# Why NumPy matters for me as a DevOps/MLOps engineer:
# - pandas (data analysis) is BUILT ON TOP of NumPy
# - scikit-learn, PyTorch, TensorFlow all use NumPy arrays internally
# - MLflow logs metrics as NumPy arrays
# - Any monitoring data (CPU usage, memory, latency) = arrays of numbers = NumPy

### What Are Python Libraries?

In [ ]:
# A library is a collection of pre-written code that you can use in your projects
# Instead of writing everything from scratch, you import a library and use its functions

# Think of it like this:
# Building a house from scratch (no library)  vs  using pre-made bricks (library)
# You COULD make your own bricks, but why waste time when great bricks already exist?

# Some important Python libraries:
#   numpy       -> numerical computations (arrays, math)     <- TODAY
#   pandas      -> data analysis (tables, CSVs, DataFrames)
#   matplotlib  -> plotting and graphs
#   seaborn     -> beautiful statistical plots
#   sklearn     -> machine learning (scikit-learn)
#   statistics  -> basic statistics (mean, median, mode)

# Every library has DOCUMENTATION — a manual/guide book
# NumPy docs: https://numpy.org/doc/stable/
#
# Pro tip from class:
# - Don't try to memorise ALL methods in a library
# - Just go through the docs once to know what's available
# - Remember the few methods that handle 80% of your tasks
# - Use the docs to look up specific methods when needed (search 'API Reference')

### Installing & Importing NumPy

In [ ]:
# INSTALLING NumPy:
# If you're using Jupyter Notebook (via Anaconda) -> NumPy is already installed!
# If you're using VS Code or plain Python -> run this in terminal:
#   pip install numpy

# In a Jupyter cell, you can also run:
# !pip install numpy    (the ! runs shell commands from inside a notebook)

# IMPORTING NumPy:
import numpy as np       # 'as np' gives it a shorter alias

# Why 'as np'?
# Instead of typing numpy.array() every time, we just type np.array()
# 'np' is the universally accepted alias for numpy — everyone uses it
# You'll see 'import numpy as np' in EVERY data science / ML tutorial

print('NumPy imported successfully!')
print('NumPy version:', np.__version__)

### Why NumPy? (Problems with Python Lists)

In [ ]:
# Before NumPy, we used Python lists for storing collections of data
# But lists have PROBLEMS when working with numbers:

# Problem 1: Lists are SLOWER
# List elements are stored at DIFFERENT memory locations (scattered)
# NumPy arrays store data CONSECUTIVELY in memory (contiguous) -> much faster

# Problem 2: You CANNOT do arithmetic directly on lists
list2 = [1, 2, 3]
# list2 + 5          # TypeError: can only concatenate list (not "int") to list
# list2 * 2          # This doesn't multiply each element — it REPEATS the list!

print(list2 * 2)      # [1, 2, 3, 1, 2, 3]  <-- repeats, NOT multiplies!

# Problem 3: Lists can hold MIXED types (not ideal for numerical work)
list1 = [1, 3, 'Hi', 'Monday']    # valid list, but you can't do math on 'Hi'!

In [ ]:
# NumPy SOLVES all of these problems!

import numpy as np

arr = np.array([1, 2, 3])

print(arr + 5)        # [6 7 8]    -> adds 5 to EACH element
print(arr * 2)        # [2 4 6]    -> multiplies EACH element by 2
print(arr ** 2)       # [1 4 9]    -> squares EACH element

# This is called VECTORISATION — applying an operation to the ENTIRE array at once
# No loops needed! NumPy handles it internally (and it's FAST)

In [ ]:
# Summary: Why NumPy arrays are better than lists for numerical work

# 1. FASTER       -> data stored consecutively in memory (contiguous)
# 2. ARITHMETIC   -> can do math operations directly on arrays (vectorisation)
# 3. MATRIX OPS   -> supports matrix multiplication, dot product, etc.
# 4. LESS MEMORY  -> arrays take less memory than equivalent lists
# 5. HOMOGENEOUS  -> all elements must be the SAME type (enforced, not optional)

# When to use lists vs NumPy arrays:
# Lists   -> mixed data types, general-purpose collections
# NumPy   -> numerical data, math operations, ML/data science work

## Creating NumPy Arrays

In [ ]:
# The basic way to create a NumPy array: np.array()
# Pass a Python list inside np.array()

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)           # [10 20 30 40 50]

# Notice: NumPy arrays print WITHOUT commas between elements
# Lists print:   [10, 20, 30, 40, 50]   <- with commas
# Arrays print:  [10 20 30 40 50]        <- without commas

### Type Coercion (Homogeneity Rule)

In [ ]:
# NumPy arrays are HOMOGENEOUS — all elements must be the SAME data type
# If you mix types, NumPy will CONVERT them to the most general type

# Conversion hierarchy: int < float < string
# (int is least general, string is most general)

# Example 1: Mix int + float -> everything becomes float
arr2 = np.array([1, 2, 3, 4.5, 6.5])
print(arr2)           # [1.  2.  3.  4.5 6.5]   <- 1 became 1.0, 2 became 2.0
print(arr2.dtype)     # float64

# Example 2: Mix int + float + string -> EVERYTHING becomes string
arr3 = np.array([1, 2, 3, 4.5, 5.6, 'Monday'])
print(arr3)           # ['1' '2' '3' '4.5' '5.6' 'Monday']   <- all strings now!
print(arr3.dtype)     # <U32 (Unicode string of max 32 characters)

# KEY POINT: If you mix types, NumPy UPCASTS to the broadest type
# int + float  -> float
# anything + string  -> string
# This ensures all elements are the SAME type (homogeneity)

### type() vs .dtype

In [ ]:
# Two different things — don't confuse them!

# type()  -> tells you the TYPE of the VARIABLE itself
# .dtype  -> tells you the TYPE of the ELEMENTS inside the array

import numpy as np

arr1 = np.array([10, 20, 30])
arr3 = np.array([1, 2, 'Monday'])

print(type(arr1))      # <class 'numpy.ndarray'>   <- the variable is an ndarray
print(type(arr3))      # <class 'numpy.ndarray'>   <- also an ndarray

print(arr1.dtype)      # int64     <- elements inside are integers
print(arr3.dtype)      # <U32      <- elements inside are strings (Unicode)

# 'ndarray' stands for 'N-dimensional array' — the core data type of NumPy
# Every NumPy array, regardless of what's inside it, is an ndarray

## NumPy Dimensions

In [ ]:
# NumPy arrays can have different DIMENSIONS (0D, 1D, 2D, 3D, ... up to 32D)
# Think of dimensions like levels of nesting:

# 0D = a single number (scalar)         -> just a value, no rows/columns
# 1D = a row of numbers (vector)        -> like a Python list
# 2D = a table of numbers (matrix)      -> rows and columns (like Excel sheet)
# 3D = a stack of tables                -> like multiple Excel sheets stacked

# Real-world analogies:
# 0D -> a single temperature reading: 36.5
# 1D -> temperature readings for one day: [36.5, 37.0, 38.2, 36.8]
# 2D -> temperature readings for a week (7 days × 4 readings): table
# 3D -> temperature readings for multiple servers over a week: stack of tables

# How to check dimensions: use .ndim attribute

### 0D Array (Scalar)

In [ ]:
# 0D array = a single value (no brackets)

import numpy as np

zero_dim = np.array(50)       # just a single number, no list brackets
print(zero_dim)               # 50
print(zero_dim.ndim)          # 0   <- zero dimensions

# COMMON MISTAKE: don't pass multiple values without brackets!
# zero = np.array(45, 46, 467)   # TypeError: array() takes from 1 to 2 arguments

# For 0D -> pass a SINGLE value: np.array(50)
# For 1D -> pass a LIST: np.array([45, 46, 467])
# The square brackets [] make all the difference!

### 1D Array (Vector)

In [ ]:
# 1D array = a single row of numbers (like a Python list)
# Created by passing a list with square brackets

one_dim = np.array([34])              # 1D with 1 element
print(one_dim)                        # [34]
print(one_dim.ndim)                   # 1

dim1 = np.array([1, 2, 3, 3, 453])   # 1D with 5 elements
print(dim1)                           # [  1   2   3   3 453]
print(dim1.ndim)                      # 1

# The key difference between 0D and 1D:
# np.array(50)     -> 0D (scalar, no brackets)  -> ndim = 0
# np.array([50])   -> 1D (vector, with brackets) -> ndim = 1
# The brackets [] add one dimension

### 2D Array (Matrix)

In [ ]:
# 2D array = a table with ROWS and COLUMNS (a matrix)
# Created by passing a list OF lists (nested list)
# Each inner list = one ROW

two_dim = np.array([[1, 2, 3],        # row 0
                    [4, 5, 6]])        # row 1

print(two_dim)
# [[1 2 3]
#  [4 5 6]]

print(two_dim.ndim)    # 2   <- two dimensions (rows + columns)

In [ ]:
# Another example: 3 rows × 4 columns

two_dim1 = np.array([[1,  2,  3,  4],     # row 0 (4 columns)
                     [5,  6,  7,  8],      # row 1 (4 columns)
                     [9, 10, 11, 12]])     # row 2 (4 columns)

print(two_dim1)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

print(two_dim1.ndim)    # 2

In [ ]:
# IMPORTANT: All rows must have the SAME number of columns!
# If rows have different lengths -> ValueError

# bad_array = np.array([[1, 2, 6, 7],     # 4 elements
#                       [5, 8, 9],          # 3 elements  <- DIFFERENT!
#                       [3, 9, 8]])         # 3 elements

# ValueError: setting an array element with a sequence.
# The requested array has an inhomogeneous shape...

# WHY? Because a 2D array is a rectangular grid (like an Excel table)
# Every row must have the same number of columns
# If they don't match, NumPy can't form a proper rectangle

### 3D Array (Stack of Matrices)

In [ ]:
# 3D array = a collection of 2D arrays stacked together
# Created by passing a list of lists of lists (triple nesting)

# Think of it as: multiple 2D tables stacked on top of each other
# Like multiple Excel sheets in one workbook

three_dim = np.array([[[1, 2],        # 2D table #0 with 1 row
                       [3, 4]]])       # (continued)

print(three_dim)
# [[[1 2]
#   [3 4]]]

print(three_dim.ndim)     # 3
print(three_dim.shape)    # (1, 2, 2)  -> 1 table, 2 rows, 2 columns

In [ ]:
# Bigger 3D example: 3 tables, each 2×2

three_dim1 = np.array([[[1, 2],         # table 0
                        [3, 4]],

                       [[1, 2],         # table 1
                        [3, 4]],

                       [[1, 2],         # table 2
                        [3, 4]]])

print(three_dim1)
# [[[1 2]
#   [3 4]]
#
#  [[1 2]
#   [3 4]]
#
#  [[1 2]
#   [3 4]]]

print(three_dim1.ndim)     # 3
print(three_dim1.shape)    # (3, 2, 2)  -> 3 tables, 2 rows each, 2 columns each
print(three_dim1.size)     # 12         -> total elements: 3 × 2 × 2 = 12

## Array Attributes — ndim, shape, size, dtype

In [ ]:
# NumPy arrays have ATTRIBUTES (properties) that describe them
# These are accessed with a DOT (not a function call — no parentheses!)

# .ndim   -> number of dimensions (0, 1, 2, 3, ...)
# .shape  -> tuple showing the size of each dimension
# .size   -> total number of elements in the array
# .dtype  -> data type of the elements (int64, float64, <U32, etc.)

import numpy as np

arr = np.array([[1, 2, 6],
                [5, 8, 9],
                [3, 9, 8]])

print('Array:')
print(arr)
print()
print('ndim :', arr.ndim)      # 2        -> 2D array
print('shape:', arr.shape)     # (3, 3)   -> 3 rows, 3 columns
print('size :', arr.size)      # 9        -> total elements: 3 × 3 = 9
print('dtype:', arr.dtype)     # int64    -> elements are 64-bit integers

In [ ]:
# How to read .shape for different dimensions:

# 0D array: shape = ()           -> empty tuple (no dimensions)
# 1D array: shape = (5,)         -> 5 elements
# 2D array: shape = (3, 4)       -> 3 rows, 4 columns
# 3D array: shape = (3, 2, 2)    -> 3 tables, 2 rows, 2 columns

# Quick formula for .size:
# size = product of all shape values
# shape (3, 4)    -> size = 3 × 4 = 12
# shape (3, 2, 2) -> size = 3 × 2 × 2 = 12

# These attributes are NOT methods — no parentheses!
# CORRECT:  arr.shape     (attribute)
# WRONG:    arr.shape()   (this would give an error)

### Quick Summary — Everything We Learned About Dimensions

In [ ]:
# Complete reference for array dimensions:

import numpy as np

# 0D — scalar (single value)
d0 = np.array(42)
print(f'0D: value={d0}, ndim={d0.ndim}, shape={d0.shape}, size={d0.size}')
# 0D: value=42, ndim=0, shape=(), size=1

# 1D — vector (row of values)
d1 = np.array([10, 20, 30, 40])
print(f'1D: value={d1}, ndim={d1.ndim}, shape={d1.shape}, size={d1.size}')
# 1D: value=[10 20 30 40], ndim=1, shape=(4,), size=4

# 2D — matrix (rows × columns)
d2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'2D: ndim={d2.ndim}, shape={d2.shape}, size={d2.size}')
# 2D: ndim=2, shape=(2, 3), size=6

# 3D — stack of matrices (tables × rows × columns)
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f'3D: ndim={d3.ndim}, shape={d3.shape}, size={d3.size}')
# 3D: ndim=3, shape=(2, 2, 2), size=8

In [ ]:
# Practice Questions:

# 1. Create a 1D NumPy array with values [5, 10, 15, 20, 25]
#    Print its ndim, shape, size, and dtype

# 2. Create a 2D array with 4 rows and 3 columns (any values you like)
#    Print its shape and verify: shape[0] = rows, shape[1] = columns
#    Also verify: size = rows × columns

# 3. Create these arrays and predict the dtype BEFORE running:
#    a) np.array([1, 2, 3])            -> dtype = ?
#    b) np.array([1, 2.0, 3])          -> dtype = ?
#    c) np.array([1, 'hello', 3.5])    -> dtype = ?
#    Then run the code and check with .dtype

# 4. What is the difference between np.array(10) and np.array([10])?
#    Create both, print ndim and shape for each. Explain the difference.

# 5. Try creating a 2D array where rows have different lengths:
#    np.array([[1, 2], [3, 4, 5]])
#    What error do you get? Why does this happen?

### DevOps / AI-MLOps Practice

In [ ]:
# NumPy is the FOUNDATION of all data work in Python
# Every monitoring metric, every ML training dataset, every log analysis
# eventually becomes a NumPy array somewhere in the pipeline

# Exercise 1: Server CPU Metrics as NumPy Array
# You have CPU usage readings (%) for 3 servers over 4 time intervals:
#   prod-web-01: [45, 62, 78, 55]
#   prod-web-02: [30, 41, 39, 35]
#   prod-db-01:  [88, 92, 95, 91]
#
# a) Create a 2D NumPy array from this data (3 rows × 4 columns)
# b) Print ndim, shape, size, dtype
# c) What does shape[0] represent? What does shape[1] represent?
# d) Verify that size = number of servers × number of readings

# Exercise 2: ML Experiment Accuracy Tracking
# You ran 5 ML experiments and recorded their accuracy scores:
#   accuracies = [0.82, 0.87, 0.91, 0.85, 0.93]
# a) Create a 1D NumPy array from this data
# b) Check the dtype — is it int or float? Why?
# c) Add 0.05 to ALL accuracies at once (simulate improvement)
# d) Multiply all by 100 to get percentages
# e) Try doing (c) and (d) with a regular Python list — what happens?
#    This shows why NumPy is essential for numerical work!

# Exercise 3: Multi-Region Latency Data (3D Array)
# You're monitoring API latency (ms) across 2 regions, each with 3 endpoints,
# recorded at 4 time intervals:
#
# Region: eastus
#   /api/users:    [120, 135, 128, 132]
#   /api/orders:   [95,  102, 98,  100]
#   /api/payments: [200, 215, 198, 205]
#
# Region: westeurope
#   /api/users:    [145, 152, 140, 148]
#   /api/orders:   [110, 118, 112, 115]
#   /api/payments: [230, 245, 225, 235]
#
# a) Create a 3D NumPy array from this data
#    Shape should be (2, 3, 4) -> 2 regions, 3 endpoints, 4 time intervals
# b) Print ndim, shape, size
# c) Verify: size should be 2 × 3 × 4 = 24
#
# This is EXACTLY how monitoring tools store time-series data internally!

# Why this matters for me as a DevOps/MLOps engineer:
# - Azure Monitor, Prometheus, Grafana all work with time-series data = arrays
# - pandas DataFrames (which I'll learn next) are built on NumPy arrays
# - Every ML model input/output is a NumPy array (scikit-learn, PyTorch, TensorFlow)
# - Understanding array shapes is CRITICAL for debugging ML pipeline errors